// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbeoWDQWpE2oWjjXyk2uv5jeKbqUmh3NY',
    appId: '1:192944303242:web:ac9ab8d55d80f8b634d173',
    messagingSenderId: '192944303242',
    projectId: 'bank-sampah-app2023',
    authDomain: 'bank-sampah-app2023.firebaseapp.com',
    storageBucket: 'bank-sampah-app2023.appspot.com',
    measurementId: 'G-GXTBD5DM66',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQ2_fZfI7YwqQ3MnqtC2i_iQNtHSeBDg4',
    appId: '1:192944303242:android:03fdaaa6a8c41c9034d173',
    messagingSenderId: '192944303242',
    projectId: 'bank-sampah-app2023',
    storageBucket: 'bank-sampah-app2023.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBs9wl3lFKl51Z7QhaRcSbEHKag1nXoiJ4',
    appId: '1:192944303242:ios:5b827c825e87ebc434d173',
    messagingSenderId: '192944303242',
    projectId: 'bank-sampah-app2023',
    storageBucket: 'bank-sampah-app2023.appspot.com',
    iosClientId: '192944303242-kq6499f7eskvj7e1djlh9j3g3pqcjhjq.apps.googleusercontent.com',
    iosBundleId: 'com.example.bankSampahApp2023',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBs9wl3lFKl51Z7QhaRcSbEHKag1nXoiJ4',
    appId: '1:192944303242:ios:cf1d7bd5e34cb7ae34d173',
    messagingSenderId: '192944303242',
    projectId: 'bank-sampah-app2023',
    storageBucket: 'bank-sampah-app2023.appspot.com',
    iosClientId: '192944303242-ctdm62fnma821jk0etb1ee2dq17qnpgh.apps.googleusercontent.com',
    iosBundleId: 'com.example.bankSampahApp2023.RunnerTests',
  );
}
